/*
 * #%L
 * wcm.io
 * %%
 * Copyright (C) 2014 wcm.io
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */
package io.wcm.caravan.pipeline.impl.cache;

import io.wcm.caravan.pipeline.cache.CachePersistencyOptions;
import io.wcm.caravan.pipeline.cache.spi.CacheAdapter;

import java.util.ArrayList;
import java.util.List;

import rx.Observable;

/**
 * Implementation of {@link CacheAdapter}.
 * Wraps a list of references to multiple cache adapters and delegates
 * {@link #getCacheKey(String servicePrefix, String descriptor)} ,
 * {@link #get(String cacheKey, CachePersistencyOptions options)},
 * {@link #put(String cacheKey, String jsonString, CachePersistencyOptions options, CacheAdapter actualCacheAdapter)}
 * method calls according to the level of cache adapters.
 */
public class MultiLayerCacheAdapter implements CacheAdapter {

  /**
   * Return multi layer cache key, if no cache key was returned by any child cache adapter.
   */
  public static final String MULTILAYER_CACHE_KEY = "Multilayer cache key";

  private List<CacheAdapter> cacheAdapters;

  /**
   * Creates a multi layer cache adapter specifying list of references cache adapters, provided in a strict order.
   * Position of each cache adapter in the list specifies its cache level and order, in which this cache adapter will be
   * called.
   * @param cacheAdapters List of {@link CacheAdapter} references
   */
  public MultiLayerCacheAdapter(List<CacheAdapter> cacheAdapters) {
    this.cacheAdapters = new ArrayList<CacheAdapter>(cacheAdapters);

  }

  /**
   * Chooses the shortest unique cache key from generated by child cache adapters. Chosen key shall be used as cache key
   * for item, stored in all wrapped caches.
   * @param servicePrefix logical name of the source service(s)
   * @param descriptor from the pipeline
   * @return the shortest unique cache key. If no key is generated, returns {@value #MULTILAYER_CACHE_KEY}.
   */
  @Override
  public String getCacheKey(String servicePrefix, String descriptor) {
    String cacheKey = null;

    for (CacheAdapter cacheAdapter : cacheAdapters) {
      String nextCacheKey = cacheAdapter.getCacheKey(servicePrefix, descriptor);
      cacheKey = chooseTheShortestCacheKey(cacheKey, nextCacheKey);
    }

    return cacheKey != null ? cacheKey : MULTILAYER_CACHE_KEY;
  }

  private String chooseTheShortestCacheKey(String actualCacheKey, String nextCacheKey) {
    return actualCacheKey == null ? nextCacheKey :
      (actualCacheKey.length() > nextCacheKey.length() ? nextCacheKey : actualCacheKey);
  }

  /**
   * Retrieves first available item from wrapped caches. If available item was found in the second or lower cache
   * level, this item will be put into the first or other higher cache levels.
   * @param cacheKey Cache key
   * @param options valid cache persistency options
   * @return an observable, than emits first found cache item. If no cache item is found, returns an empty observable.
   */
  @Override
  public Observable<String> get(String cacheKey, CachePersistencyOptions options) {
    return Observable.create(subscriber -> {
      Observable<String> result = Observable.empty();
      CacheAdapter actualCacheAdapter = null;
      for (CacheAdapter cacheAdapter : cacheAdapters) {
        result = cacheAdapter.get(cacheKey, options).cache();
        if (!result.isEmpty().toBlocking().first()) {
          actualCacheAdapter = cacheAdapter;
          break;
        }
      }
      if (actualCacheAdapter != null) {
        String cachedValue = getCacheEntry(result);
        if (cachedValue != null) {
          subscriber.onNext(cachedValue);
          put(cacheKey, cachedValue, options, actualCacheAdapter);
        }
      }
      subscriber.onCompleted();
    });
  }

  private String getCacheEntry(Observable<String> observable) {
    return observable.count().toBlocking().single() > 0 ? observable.toBlocking().first() : null;
  }

  /*
   * Puts cache item into the caches, which are specified to be earlier than actual CacheAdapter. Call this method, if expected that
   * actual CacheAdapter and later caches already have stored item.
   */
  private void put(String cacheKey, String jsonString, CachePersistencyOptions options, CacheAdapter actualCacheAdapter) {
    for (CacheAdapter cacheAdapter : cacheAdapters) {
      if (cacheAdapter != actualCacheAdapter) {
        cacheAdapter.put(cacheKey, jsonString, options);
      }
      else {
        break;
      }
    }
  }

  /**
   * Store an item in each wrapped cache.
   * @param cacheKey Cache key
   * @param jsonString JSON data
   * @param options valid cache persistency options
   */
  @Override
  public void put(String cacheKey, String jsonString, CachePersistencyOptions options) {
    for (CacheAdapter cacheAdapter : cacheAdapters) {
      cacheAdapter.put(cacheKey, jsonString, options);
    }
  }

}
